name: Lint and Test Project
on:
  pull_request:
jobs:
  ci:
    strategy:
      matrix:
        java: ['8', '11', '17']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
          restore-keys: ${{ runner.os }}-deps-

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@8.0
        with:
          cli: 1.11.1.1149
          clj-kondo: 2022.06.22

      - name: Lint project
        run: clj-kondo --lint src:test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

      - name: Format project
        run: clojure -M:cljfmt check

      - name: Run Unit tests
        run: clojure -T:build test
